In [1]:
import tensorflow as tf

D:\Users\snandan.ORADEV\AppData\Local\Continuum\anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [4]:
M = tf.constant([[1,2],[3,4]],dtype='float32')
v = tf.constant([5,6],dtype='float32')

In [5]:
M+v

<tf.Tensor 'add:0' shape=(2, 2) dtype=float32>

In [6]:
sess = tf.Session()
sess.run(M+v)

array([[ 6.,  8.],
       [ 8., 10.]], dtype=float32)

In [7]:
sess.run(M*v)

array([[ 5., 12.],
       [15., 24.]], dtype=float32)

In [8]:
sess.run(tf.matmul(M, tf.reshape(v, [2,1])))

array([[17.],
       [39.]], dtype=float32)